Default: &defaults
  user: gitolist
  password: gitolistadmin
  host: localhost
  port: 27017
  database: gitolist
  poolsize: 10

Development:
  <<: *defaults

Test:
  database: gitolist_test
  <<: *defaults

Staging:
  database: gitolist_staging
  poolsize: 100
  <<: *defaults

Production:
  database: gitolist_production
  poolsize: 100
  <<: *defaults
